### PR TITLE
Updated jbenet links to multiformats links

### PR DESCRIPTION
**Pull request by RichardLitt**
Part of #13. Still needs for the npm package to be republished.

### CODE REVIEW

**Comment by RichardLitt** [comment]
@jbenet Merge and republish npm package, if you can. Thanks.

**Comment by dignifiedquire** [comment]
@RichardLitt have you checked that all the ci services are running?

**Comment by RichardLitt** [comment]
Ahhh those too. No.

**Comment by RichardLitt** [comment]
@dignifiedquire How does this look? I can merge it and publish, I have access now.

**Comment by jbenet** [comment]
This LGTM. CI seems to have run :)

**Comment by RichardLitt** [comment]
@jbenet I don't have permission to `npm publish` this.

**Pull request merged**
