### PR TITLE
Add lead-maintainer

### PR DESCRIPTION
**Pull request by diasdavid**
ref: https://github.com/ipfs/community/pull/301#issuecomment-384762478

### CODE REVIEW

**Comment by diasdavid** [comment]
This is the first PR towards the goal of https://github.com/ipfs/community/pull/301#issuecomment-384762478

I've updated the permissions of this repo to

image

I believe these restrictions to be sane, but would like someone to double check.

**Comment by VictorBjelkholm** [comment]
The "require status checks to pass before merging" option needs to have a status check that is marked as required, otherwise this option does nothing. Should probably be the `continuous-integration/jenkins/pr-merge` status check as that one includes the full jenkins build on merge.

I think "Restrict who can push to this branch" should be activated and no one should be allowed to push directly to master. From the screenshot, you'll be able to push but no one else.

**Comment by diasdavid** [comment]
@VictorBjelkholm Thank you! Just updated to

image

**Comment by diasdavid** [comment]
@VictorBjelkholm would you like to have the honor to review this PR so that I can merge it ? :)

**Comment by VictorBjelkholm** [comment]
Awesome, looks good!

**Comment by VictorBjelkholm** [comment]
>  The target branch requires all commits to be signed. Learn more about signing commits. 

Working well for this repo at least! :)

**Comment by diasdavid** [comment]
@VictorBjelkholm you'll need to approve again

**Comment by vmx** [comment]
@diasdavid The screenshot shows that "Require signed commits: Commits pushed to this branch must have verified signatures." is ticked. Is that intentional and a must?

**Pull request merged**
