### PR TITLE
Add Holochain prefixes for Keys, Addresses and Signatures

### PR DESCRIPTION
**Pull request by pjkundert**

### CODE REVIEW

**Comment by hugomrdias** [comment]
this repo now uses a script to sync https://raw.githubusercontent.com/multiformats/multicodec/master/table.csv

so please add these to the above table and run `npm run update-constants` and PR the changes. 

thank you

**Comment by pjkundert** [comment]
@hugomrdias  I'm not sure where to find the package.json containing the 'update-constants' target; it is neither in js-multihash or multicodec.

**Comment by hugomrdias** [comment]
https://github.com/multiformats/js-multihash/blob/master/package.json#L19

**Comment by pjkundert** [comment]
Sorry!  I was looking in my own forked repo.  Thanks,

**Pull request closed without merging**
